from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name=''),
    path('hello', views.hello, name='hello'),
    path('reg', views.reg, name='reg'),
    path('reg1', views.reg1, name='reg1'),
    path('settings', views.settings, name='setting'),
    path('accounts/profile/', views.profile, name='profile'),
    path('user/<str:un>/', views.user, name='user'),
    path('post/<int:pid>/', views.post, name='post'),
    path('like/<int:lid>/', views.like, name='like'),
    path('nl/<int:lid>/', views.nl, name='like'),
    path('ns/<int:sid>/', views.ns, name='subscribe'),
    path('lent', views.lent, name='lenta'),
    path('search', views.search, name='search'),
    path('students', views.students, name='students'),
    path('filtrs/<int:fid>/', views.filtrs, name='filtrs'),
    path('finds', views.finds, name='finds'),
    path('coms', views.coms, name='coms'),
    path('filtrc/<int:fid>/', views.filtrc, name='filtrc'),
    path('eves', views.eves, name='eves'),
    path('filtre/<int:fid>/', views.filtre, name='filtre'),
    path('spec', views.spec, name='spec'),
    path('group', views.group, name='group'),
    path('community/<int:cid>/', views.community, name='community'),
    path('comlike/<int:lid>/', views.comlike, name='comlike'),
    path('comnl/<int:lid>/', views.comnl, name='comlike'),
    path('compost/<int:pid>/', views.compost, name='compost'),
    path('am/<int:cid>/', views.am, name='enjoy'),
    path('event/<int:eid>/', views.event, name='event'),
    path('evenlike/<int:lid>/', views.evenlike, name='evenlike'),
    path('evennl/<int:lid>/', views.evennl, name='evenlike'),
    path('epost/<int:pid>/', views.epost, name='epost'),
    path('ap/<int:eid>/', views.ap, name='come'),
]